name: KillMeiKillU
version: 1.0
main: org.firstplugin.killmeikillu.KillMeiKillU
api-version: 1.19
commands:
  kmku:
    description: KillMeiKillU main command
    usage: /kmku <subcommand> [args]
    aliases: [killmeikillu]
    permission: killmeikillu.base
    permission-message: You do not have permission to use this command.
    subcommands:
      hello:
        description: Says hello
        usage: /kmku hello
        permission: killmeikillu.hello
